title: Hoppy Christams! A guide to christmas beers
description: The website for the group Applied Macaque analysis
show_downloads: False
github.is_project_page: False
theme: jekyll-theme-cayman
navigation:
  - title: Home
    url: /A
  - title: Example
    url: /example
  - title: test
    url: /
   
