theme: Slate
title: Hoppy Christams! A guide to christmas beers
description: The website for the group Applied Macaque analysis
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
