title: Hoppy Christams! A guide to christmas beers
description: The website for the group Applied Macaque analysis
show_downloads: True
theme: jekyll-theme-cayman
navigation:
  - title: Home
    url: /
